try:
    print('eeee')
    prr()
except Exception as er:
    print(er)